# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Tue Nov  8 02:07:54 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialogClass(object):
    def setupUi(self, SettingsDialogClass):
        SettingsDialogClass.setObjectName(_fromUtf8("SettingsDialogClass"))
        SettingsDialogClass.resize(532, 736)
        self.gridLayout = QtGui.QGridLayout(SettingsDialogClass)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialogClass)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(SettingsDialogClass)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.stop_events_down_btn = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_events_down_btn.sizePolicy().hasHeightForWidth())
        self.stop_events_down_btn.setSizePolicy(sizePolicy)
        self.stop_events_down_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.stop_events_down_btn.setObjectName(_fromUtf8("stop_events_down_btn"))
        self.gridLayout_10.addWidget(self.stop_events_down_btn, 4, 0, 1, 1)
        self.stop_events_del_btn = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_events_del_btn.sizePolicy().hasHeightForWidth())
        self.stop_events_del_btn.setSizePolicy(sizePolicy)
        self.stop_events_del_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.stop_events_del_btn.setObjectName(_fromUtf8("stop_events_del_btn"))
        self.gridLayout_10.addWidget(self.stop_events_del_btn, 4, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_6)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_10.addWidget(self.label_16, 2, 0, 1, 3)
        self.stop_notes_chk = QtGui.QCheckBox(self.groupBox_6)
        self.stop_notes_chk.setObjectName(_fromUtf8("stop_notes_chk"))
        self.gridLayout_10.addWidget(self.stop_notes_chk, 0, 0, 1, 3)
        self.stop_events_up_btn = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_events_up_btn.sizePolicy().hasHeightForWidth())
        self.stop_events_up_btn.setSizePolicy(sizePolicy)
        self.stop_events_up_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.stop_events_up_btn.setObjectName(_fromUtf8("stop_events_up_btn"))
        self.gridLayout_10.addWidget(self.stop_events_up_btn, 3, 0, 1, 1)
        self.stop_events_add_btn = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_events_add_btn.sizePolicy().hasHeightForWidth())
        self.stop_events_add_btn.setSizePolicy(sizePolicy)
        self.stop_events_add_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.stop_events_add_btn.setObjectName(_fromUtf8("stop_events_add_btn"))
        self.gridLayout_10.addWidget(self.stop_events_add_btn, 3, 2, 1, 1)
        self.stop_events_table = QtGui.QTableView(self.groupBox_6)
        self.stop_events_table.setMaximumSize(QtCore.QSize(16777215, 80))
        self.stop_events_table.setObjectName(_fromUtf8("stop_events_table"))
        self.stop_events_table.verticalHeader().setVisible(False)
        self.gridLayout_10.addWidget(self.stop_events_table, 3, 1, 2, 1)
        self.line_4 = QtGui.QFrame(self.groupBox_6)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_10.addWidget(self.line_4, 1, 0, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.auto_connect_hw_radio = QtGui.QRadioButton(self.groupBox_4)
        self.auto_connect_hw_radio.setChecked(True)
        self.auto_connect_hw_radio.setObjectName(_fromUtf8("auto_connect_hw_radio"))
        self.auto_connect_group = QtGui.QButtonGroup(SettingsDialogClass)
        self.auto_connect_group.setObjectName(_fromUtf8("auto_connect_group"))
        self.auto_connect_group.addButton(self.auto_connect_hw_radio)
        self.horizontalLayout_3.addWidget(self.auto_connect_hw_radio)
        self.auto_connect_sw_radio = QtGui.QRadioButton(self.groupBox_4)
        self.auto_connect_sw_radio.setChecked(False)
        self.auto_connect_sw_radio.setObjectName(_fromUtf8("auto_connect_sw_radio"))
        self.auto_connect_group.addButton(self.auto_connect_sw_radio)
        self.horizontalLayout_3.addWidget(self.auto_connect_sw_radio)
        self.auto_connect_all_radio = QtGui.QRadioButton(self.groupBox_4)
        self.auto_connect_all_radio.setObjectName(_fromUtf8("auto_connect_all_radio"))
        self.auto_connect_group.addButton(self.auto_connect_all_radio)
        self.horizontalLayout_3.addWidget(self.auto_connect_all_radio)
        self.auto_connect_custom_radio = QtGui.QRadioButton(self.groupBox_4)
        self.auto_connect_custom_radio.setObjectName(_fromUtf8("auto_connect_custom_radio"))
        self.auto_connect_group.addButton(self.auto_connect_custom_radio)
        self.horizontalLayout_3.addWidget(self.auto_connect_custom_radio)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 3, 0, 1, 2)
        self.line_6 = QtGui.QFrame(self.groupBox_4)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_6.addWidget(self.line_6, 1, 0, 1, 2)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.auto_connect_list = QtGui.QListView(self.groupBox_4)
        self.auto_connect_list.setEnabled(False)
        self.auto_connect_list.setMaximumSize(QtCore.QSize(16777215, 80))
        self.auto_connect_list.setObjectName(_fromUtf8("auto_connect_list"))
        self.gridLayout_11.addWidget(self.auto_connect_list, 1, 3, 3, 1)
        self.auto_connect_add_btn = QtGui.QPushButton(self.groupBox_4)
        self.auto_connect_add_btn.setEnabled(False)
        self.auto_connect_add_btn.setObjectName(_fromUtf8("auto_connect_add_btn"))
        self.gridLayout_11.addWidget(self.auto_connect_add_btn, 2, 4, 1, 1)
        self.auto_connect_del_btn = QtGui.QPushButton(self.groupBox_4)
        self.auto_connect_del_btn.setEnabled(False)
        self.auto_connect_del_btn.setObjectName(_fromUtf8("auto_connect_del_btn"))
        self.gridLayout_11.addWidget(self.auto_connect_del_btn, 3, 4, 1, 1)
        self.blacklist_del_btn = QtGui.QPushButton(self.groupBox_4)
        self.blacklist_del_btn.setObjectName(_fromUtf8("blacklist_del_btn"))
        self.gridLayout_11.addWidget(self.blacklist_del_btn, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 1, 4, 1, 1)
        self.blacklist_add_btn = QtGui.QPushButton(self.groupBox_4)
        self.blacklist_add_btn.setObjectName(_fromUtf8("blacklist_add_btn"))
        self.gridLayout_11.addWidget(self.blacklist_add_btn, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 1, 1, 1, 1)
        self.blacklist_list = QtGui.QListView(self.groupBox_4)
        self.blacklist_list.setMaximumSize(QtCore.QSize(16777215, 80))
        self.blacklist_list.setObjectName(_fromUtf8("blacklist_list"))
        self.gridLayout_11.addWidget(self.blacklist_list, 1, 0, 3, 1)
        self.line_5 = QtGui.QFrame(self.groupBox_4)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_11.addWidget(self.line_5, 0, 2, 4, 1)
        self.blacklist_lbl = QtGui.QLabel(self.groupBox_4)
        self.blacklist_lbl.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.blacklist_lbl.setWordWrap(True)
        self.blacklist_lbl.setObjectName(_fromUtf8("blacklist_lbl"))
        self.gridLayout_11.addWidget(self.blacklist_lbl, 0, 0, 1, 2)
        self.whitelist_lbl = QtGui.QLabel(self.groupBox_4)
        self.whitelist_lbl.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.whitelist_lbl.setWordWrap(True)
        self.whitelist_lbl.setMargin(1)
        self.whitelist_lbl.setObjectName(_fromUtf8("whitelist_lbl"))
        self.gridLayout_11.addWidget(self.whitelist_lbl, 0, 3, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_11, 2, 0, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.trigger_list = QtGui.QListView(self.groupBox_3)
        self.trigger_list.setMaximumSize(QtCore.QSize(16777215, 80))
        self.trigger_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.trigger_list.setObjectName(_fromUtf8("trigger_list"))
        self.gridLayout_4.addWidget(self.trigger_list, 3, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.trigger_add_btn = QtGui.QPushButton(self.groupBox_3)
        self.trigger_add_btn.setMinimumSize(QtCore.QSize(20, 0))
        self.trigger_add_btn.setObjectName(_fromUtf8("trigger_add_btn"))
        self.verticalLayout.addWidget(self.trigger_add_btn)
        self.trigger_del_btn = QtGui.QPushButton(self.groupBox_3)
        self.trigger_del_btn.setMinimumSize(QtCore.QSize(20, 0))
        self.trigger_del_btn.setObjectName(_fromUtf8("trigger_del_btn"))
        self.verticalLayout.addWidget(self.trigger_del_btn)
        self.gridLayout_4.addLayout(self.verticalLayout, 3, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.record_add_btn = QtGui.QPushButton(self.groupBox_3)
        self.record_add_btn.setMinimumSize(QtCore.QSize(20, 0))
        self.record_add_btn.setObjectName(_fromUtf8("record_add_btn"))
        self.verticalLayout_2.addWidget(self.record_add_btn)
        self.record_del_btn = QtGui.QPushButton(self.groupBox_3)
        self.record_del_btn.setMinimumSize(QtCore.QSize(20, 0))
        self.record_del_btn.setObjectName(_fromUtf8("record_del_btn"))
        self.verticalLayout_2.addWidget(self.record_del_btn)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 3, 3, 1, 1)
        self.record_list = QtGui.QListView(self.groupBox_3)
        self.record_list.setMaximumSize(QtCore.QSize(16777215, 80))
        self.record_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.record_list.setObjectName(_fromUtf8("record_list"))
        self.gridLayout_4.addWidget(self.record_list, 3, 2, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.time_threshold_spin = QtGui.QSpinBox(self.groupBox_3)
        self.time_threshold_spin.setMaximumSize(QtCore.QSize(48, 16777215))
        self.time_threshold_spin.setMinimum(50)
        self.time_threshold_spin.setMaximum(200)
        self.time_threshold_spin.setSingleStep(10)
        self.time_threshold_spin.setProperty("value", 100)
        self.time_threshold_spin.setObjectName(_fromUtf8("time_threshold_spin"))
        self.gridLayout_5.addWidget(self.time_threshold_spin, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 5)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 2, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 2, 2, 1, 1)
        self.ignore_list = QtGui.QListView(self.groupBox_3)
        self.ignore_list.setMaximumSize(QtCore.QSize(16777215, 80))
        self.ignore_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.ignore_list.setObjectName(_fromUtf8("ignore_list"))
        self.gridLayout_4.addWidget(self.ignore_list, 3, 4, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_4.addWidget(self.line_2, 1, 0, 1, 5)
        self.gridLayout_7.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.last_event_limit_spin = QtGui.QSpinBox(self.groupBox)
        self.last_event_limit_spin.setMaximumSize(QtCore.QSize(48, 16777215))
        self.last_event_limit_spin.setMinimum(2)
        self.last_event_limit_spin.setMaximum(60)
        self.last_event_limit_spin.setProperty("value", 10)
        self.last_event_limit_spin.setObjectName(_fromUtf8("last_event_limit_spin"))
        self.gridLayout_2.addWidget(self.last_event_limit_spin, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.startup_chk = QtGui.QCheckBox(self.groupBox)
        self.startup_chk.setObjectName(_fromUtf8("startup_chk"))
        self.gridLayout_2.addWidget(self.startup_chk, 0, 0, 1, 2)
        self.max_size_spin = QtGui.QSpinBox(self.groupBox)
        self.max_size_spin.setMaximumSize(QtCore.QSize(48, 16777215))
        self.max_size_spin.setMinimum(16)
        self.max_size_spin.setMaximum(150)
        self.max_size_spin.setProperty("value", 16)
        self.max_size_spin.setObjectName(_fromUtf8("max_size_spin"))
        self.gridLayout_2.addWidget(self.max_size_spin, 2, 1, 1, 1)
        self.ignore_doublenote_chk = QtGui.QCheckBox(self.groupBox)
        self.ignore_doublenote_chk.setObjectName(_fromUtf8("ignore_doublenote_chk"))
        self.gridLayout_2.addWidget(self.ignore_doublenote_chk, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.toggle_mode_chk = QtGui.QCheckBox(self.groupBox_2)
        self.toggle_mode_chk.setObjectName(_fromUtf8("toggle_mode_chk"))
        self.gridLayout_3.addWidget(self.toggle_mode_chk, 2, 0, 1, 7)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 5, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 4, 3, 1, 1)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ctrl_auto_connect_chk = QtGui.QCheckBox(self.groupBox_2)
        self.ctrl_auto_connect_chk.setObjectName(_fromUtf8("ctrl_auto_connect_chk"))
        self.horizontalLayout_2.addWidget(self.ctrl_auto_connect_chk)
        self.ctrl_auto_connect_edit = QtGui.QLineEdit(self.groupBox_2)
        self.ctrl_auto_connect_edit.setEnabled(False)
        self.ctrl_auto_connect_edit.setObjectName(_fromUtf8("ctrl_auto_connect_edit"))
        self.horizontalLayout_2.addWidget(self.ctrl_auto_connect_edit)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 7)
        self.enable_value_spin = QtGui.QSpinBox(self.groupBox_2)
        self.enable_value_spin.setMaximumSize(QtCore.QSize(48, 16777215))
        self.enable_value_spin.setMinimum(0)
        self.enable_value_spin.setMaximum(127)
        self.enable_value_spin.setObjectName(_fromUtf8("enable_value_spin"))
        self.gridLayout_3.addWidget(self.enable_value_spin, 3, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 3, 3, 1, 1)
        self.disable_value_spin = QtGui.QSpinBox(self.groupBox_2)
        self.disable_value_spin.setMaximumSize(QtCore.QSize(48, 16777215))
        self.disable_value_spin.setMinimum(0)
        self.disable_value_spin.setMaximum(127)
        self.disable_value_spin.setProperty("value", 0)
        self.disable_value_spin.setObjectName(_fromUtf8("disable_value_spin"))
        self.gridLayout_3.addWidget(self.disable_value_spin, 4, 4, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 3, 5, 1, 1)
        self.stop_value_spin = QtGui.QSpinBox(self.groupBox_2)
        self.stop_value_spin.setMaximumSize(QtCore.QSize(48, 16777215))
        self.stop_value_spin.setMinimum(0)
        self.stop_value_spin.setMaximum(127)
        self.stop_value_spin.setProperty("value", 0)
        self.stop_value_spin.setObjectName(_fromUtf8("stop_value_spin"))
        self.gridLayout_3.addWidget(self.stop_value_spin, 5, 4, 1, 1)
        self.disable_chan_spin = QtGui.QSpinBox(self.groupBox_2)
        self.disable_chan_spin.setMaximum(16)
        self.disable_chan_spin.setObjectName(_fromUtf8("disable_chan_spin"))
        self.gridLayout_3.addWidget(self.disable_chan_spin, 4, 6, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 5, 5, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 4, 5, 1, 1)
        self.stop_chan_spin = QtGui.QSpinBox(self.groupBox_2)
        self.stop_chan_spin.setMaximum(16)
        self.stop_chan_spin.setObjectName(_fromUtf8("stop_chan_spin"))
        self.gridLayout_3.addWidget(self.stop_chan_spin, 5, 6, 1, 1)
        self.enable_chan_spin = QtGui.QSpinBox(self.groupBox_2)
        self.enable_chan_spin.setMaximum(16)
        self.enable_chan_spin.setObjectName(_fromUtf8("enable_chan_spin"))
        self.gridLayout_3.addWidget(self.enable_chan_spin, 3, 6, 1, 1)
        self.enable_param_combo = ParamCombo(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enable_param_combo.sizePolicy().hasHeightForWidth())
        self.enable_param_combo.setSizePolicy(sizePolicy)
        self.enable_param_combo.setEditable(True)
        self.enable_param_combo.setObjectName(_fromUtf8("enable_param_combo"))
        self.gridLayout_3.addWidget(self.enable_param_combo, 3, 2, 1, 1)
        self.stop_combo = QtGui.QComboBox(self.groupBox_2)
        self.stop_combo.setObjectName(_fromUtf8("stop_combo"))
        self.stop_combo.addItem(_fromUtf8(""))
        self.stop_combo.addItem(_fromUtf8(""))
        self.stop_combo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.stop_combo, 5, 1, 1, 1)
        self.enable_combo = QtGui.QComboBox(self.groupBox_2)
        self.enable_combo.setObjectName(_fromUtf8("enable_combo"))
        self.enable_combo.addItem(_fromUtf8(""))
        self.enable_combo.addItem(_fromUtf8(""))
        self.enable_combo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.enable_combo, 3, 1, 1, 1)
        self.disable_combo = QtGui.QComboBox(self.groupBox_2)
        self.disable_combo.setObjectName(_fromUtf8("disable_combo"))
        self.disable_combo.addItem(_fromUtf8(""))
        self.disable_combo.addItem(_fromUtf8(""))
        self.disable_combo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.disable_combo, 4, 1, 1, 1)
        self.disable_param_combo = ParamCombo(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disable_param_combo.sizePolicy().hasHeightForWidth())
        self.disable_param_combo.setSizePolicy(sizePolicy)
        self.disable_param_combo.setEditable(True)
        self.disable_param_combo.setObjectName(_fromUtf8("disable_param_combo"))
        self.gridLayout_3.addWidget(self.disable_param_combo, 4, 2, 1, 1)
        self.stop_param_combo = ParamCombo(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_param_combo.sizePolicy().hasHeightForWidth())
        self.stop_param_combo.setSizePolicy(sizePolicy)
        self.stop_param_combo.setEditable(True)
        self.stop_param_combo.setObjectName(_fromUtf8("stop_param_combo"))
        self.gridLayout_3.addWidget(self.stop_param_combo, 5, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.fb_stop_add_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_stop_add_btn.sizePolicy().hasHeightForWidth())
        self.fb_stop_add_btn.setSizePolicy(sizePolicy)
        self.fb_stop_add_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_stop_add_btn.setObjectName(_fromUtf8("fb_stop_add_btn"))
        self.gridLayout_9.addWidget(self.fb_stop_add_btn, 11, 2, 1, 1)
        self.fb_disable_down_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_disable_down_btn.sizePolicy().hasHeightForWidth())
        self.fb_disable_down_btn.setSizePolicy(sizePolicy)
        self.fb_disable_down_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_disable_down_btn.setObjectName(_fromUtf8("fb_disable_down_btn"))
        self.gridLayout_9.addWidget(self.fb_disable_down_btn, 8, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.groupBox_5)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_9.addWidget(self.line_3, 1, 0, 1, 3)
        self.fb_disable_table = QtGui.QTableView(self.groupBox_5)
        self.fb_disable_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.fb_disable_table.setObjectName(_fromUtf8("fb_disable_table"))
        self.fb_disable_table.verticalHeader().setVisible(False)
        self.gridLayout_9.addWidget(self.fb_disable_table, 7, 1, 2, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_9.addWidget(self.label_15, 2, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fb_auto_connect_chk = QtGui.QCheckBox(self.groupBox_5)
        self.fb_auto_connect_chk.setObjectName(_fromUtf8("fb_auto_connect_chk"))
        self.horizontalLayout.addWidget(self.fb_auto_connect_chk)
        self.fb_auto_connect_edit = QtGui.QLineEdit(self.groupBox_5)
        self.fb_auto_connect_edit.setEnabled(False)
        self.fb_auto_connect_edit.setObjectName(_fromUtf8("fb_auto_connect_edit"))
        self.horizontalLayout.addWidget(self.fb_auto_connect_edit)
        self.gridLayout_9.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(20, 4, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem3, 5, 0, 1, 3)
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_9.addWidget(self.label_17, 6, 0, 1, 2)
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_9.addWidget(self.label_18, 10, 0, 1, 2)
        self.fb_play_table = QtGui.QTableView(self.groupBox_5)
        self.fb_play_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.fb_play_table.setObjectName(_fromUtf8("fb_play_table"))
        self.fb_play_table.verticalHeader().setVisible(False)
        self.gridLayout_9.addWidget(self.fb_play_table, 15, 1, 2, 1)
        self.fb_enable_add_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_enable_add_btn.sizePolicy().hasHeightForWidth())
        self.fb_enable_add_btn.setSizePolicy(sizePolicy)
        self.fb_enable_add_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_enable_add_btn.setObjectName(_fromUtf8("fb_enable_add_btn"))
        self.gridLayout_9.addWidget(self.fb_enable_add_btn, 3, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 4, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem4, 13, 0, 1, 3)
        self.fb_enable_table = QtGui.QTableView(self.groupBox_5)
        self.fb_enable_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.fb_enable_table.setObjectName(_fromUtf8("fb_enable_table"))
        self.fb_enable_table.verticalHeader().setVisible(False)
        self.gridLayout_9.addWidget(self.fb_enable_table, 3, 1, 2, 1)
        self.fb_play_add_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_play_add_btn.sizePolicy().hasHeightForWidth())
        self.fb_play_add_btn.setSizePolicy(sizePolicy)
        self.fb_play_add_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_play_add_btn.setObjectName(_fromUtf8("fb_play_add_btn"))
        self.gridLayout_9.addWidget(self.fb_play_add_btn, 15, 2, 1, 1)
        self.fb_stop_del_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_stop_del_btn.sizePolicy().hasHeightForWidth())
        self.fb_stop_del_btn.setSizePolicy(sizePolicy)
        self.fb_stop_del_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_stop_del_btn.setObjectName(_fromUtf8("fb_stop_del_btn"))
        self.gridLayout_9.addWidget(self.fb_stop_del_btn, 12, 2, 1, 1)
        self.fb_play_del_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_play_del_btn.sizePolicy().hasHeightForWidth())
        self.fb_play_del_btn.setSizePolicy(sizePolicy)
        self.fb_play_del_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_play_del_btn.setObjectName(_fromUtf8("fb_play_del_btn"))
        self.gridLayout_9.addWidget(self.fb_play_del_btn, 16, 2, 1, 1)
        self.fb_enable_del_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_enable_del_btn.sizePolicy().hasHeightForWidth())
        self.fb_enable_del_btn.setSizePolicy(sizePolicy)
        self.fb_enable_del_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_enable_del_btn.setObjectName(_fromUtf8("fb_enable_del_btn"))
        self.gridLayout_9.addWidget(self.fb_enable_del_btn, 4, 2, 1, 1)
        self.fb_enable_up_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_enable_up_btn.sizePolicy().hasHeightForWidth())
        self.fb_enable_up_btn.setSizePolicy(sizePolicy)
        self.fb_enable_up_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_enable_up_btn.setObjectName(_fromUtf8("fb_enable_up_btn"))
        self.gridLayout_9.addWidget(self.fb_enable_up_btn, 3, 0, 1, 1)
        self.fb_disable_add_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_disable_add_btn.sizePolicy().hasHeightForWidth())
        self.fb_disable_add_btn.setSizePolicy(sizePolicy)
        self.fb_disable_add_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_disable_add_btn.setObjectName(_fromUtf8("fb_disable_add_btn"))
        self.gridLayout_9.addWidget(self.fb_disable_add_btn, 7, 2, 1, 1)
        self.fb_disable_del_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_disable_del_btn.sizePolicy().hasHeightForWidth())
        self.fb_disable_del_btn.setSizePolicy(sizePolicy)
        self.fb_disable_del_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_disable_del_btn.setObjectName(_fromUtf8("fb_disable_del_btn"))
        self.gridLayout_9.addWidget(self.fb_disable_del_btn, 8, 2, 1, 1)
        self.fb_stop_up_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_stop_up_btn.sizePolicy().hasHeightForWidth())
        self.fb_stop_up_btn.setSizePolicy(sizePolicy)
        self.fb_stop_up_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_stop_up_btn.setObjectName(_fromUtf8("fb_stop_up_btn"))
        self.gridLayout_9.addWidget(self.fb_stop_up_btn, 11, 0, 1, 1)
        self.fb_enable_down_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_enable_down_btn.sizePolicy().hasHeightForWidth())
        self.fb_enable_down_btn.setSizePolicy(sizePolicy)
        self.fb_enable_down_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_enable_down_btn.setObjectName(_fromUtf8("fb_enable_down_btn"))
        self.gridLayout_9.addWidget(self.fb_enable_down_btn, 4, 0, 1, 1)
        self.fb_stop_down_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_stop_down_btn.sizePolicy().hasHeightForWidth())
        self.fb_stop_down_btn.setSizePolicy(sizePolicy)
        self.fb_stop_down_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_stop_down_btn.setObjectName(_fromUtf8("fb_stop_down_btn"))
        self.gridLayout_9.addWidget(self.fb_stop_down_btn, 12, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_9.addWidget(self.label_19, 14, 0, 1, 2)
        self.fb_disable_up_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_disable_up_btn.sizePolicy().hasHeightForWidth())
        self.fb_disable_up_btn.setSizePolicy(sizePolicy)
        self.fb_disable_up_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_disable_up_btn.setObjectName(_fromUtf8("fb_disable_up_btn"))
        self.gridLayout_9.addWidget(self.fb_disable_up_btn, 7, 0, 1, 1)
        self.fb_play_up_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_play_up_btn.sizePolicy().hasHeightForWidth())
        self.fb_play_up_btn.setSizePolicy(sizePolicy)
        self.fb_play_up_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_play_up_btn.setObjectName(_fromUtf8("fb_play_up_btn"))
        self.gridLayout_9.addWidget(self.fb_play_up_btn, 15, 0, 1, 1)
        self.fb_play_down_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fb_play_down_btn.sizePolicy().hasHeightForWidth())
        self.fb_play_down_btn.setSizePolicy(sizePolicy)
        self.fb_play_down_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.fb_play_down_btn.setObjectName(_fromUtf8("fb_play_down_btn"))
        self.gridLayout_9.addWidget(self.fb_play_down_btn, 16, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 4, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem5, 9, 0, 1, 3)
        self.fb_stop_table = QtGui.QTableView(self.groupBox_5)
        self.fb_stop_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.fb_stop_table.setObjectName(_fromUtf8("fb_stop_table"))
        self.fb_stop_table.verticalHeader().setVisible(False)
        self.gridLayout_9.addWidget(self.fb_stop_table, 11, 1, 2, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(SettingsDialogClass)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialogClass.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialogClass.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialogClass)
        SettingsDialogClass.setTabOrder(self.startup_chk, self.last_event_limit_spin)
        SettingsDialogClass.setTabOrder(self.last_event_limit_spin, self.max_size_spin)
        SettingsDialogClass.setTabOrder(self.max_size_spin, self.ignore_doublenote_chk)
        SettingsDialogClass.setTabOrder(self.ignore_doublenote_chk, self.auto_connect_hw_radio)
        SettingsDialogClass.setTabOrder(self.auto_connect_hw_radio, self.auto_connect_sw_radio)
        SettingsDialogClass.setTabOrder(self.auto_connect_sw_radio, self.auto_connect_all_radio)
        SettingsDialogClass.setTabOrder(self.auto_connect_all_radio, self.auto_connect_custom_radio)
        SettingsDialogClass.setTabOrder(self.auto_connect_custom_radio, self.blacklist_list)
        SettingsDialogClass.setTabOrder(self.blacklist_list, self.blacklist_add_btn)
        SettingsDialogClass.setTabOrder(self.blacklist_add_btn, self.blacklist_del_btn)
        SettingsDialogClass.setTabOrder(self.blacklist_del_btn, self.auto_connect_list)
        SettingsDialogClass.setTabOrder(self.auto_connect_list, self.auto_connect_add_btn)
        SettingsDialogClass.setTabOrder(self.auto_connect_add_btn, self.auto_connect_del_btn)
        SettingsDialogClass.setTabOrder(self.auto_connect_del_btn, self.time_threshold_spin)
        SettingsDialogClass.setTabOrder(self.time_threshold_spin, self.trigger_list)
        SettingsDialogClass.setTabOrder(self.trigger_list, self.trigger_add_btn)
        SettingsDialogClass.setTabOrder(self.trigger_add_btn, self.trigger_del_btn)
        SettingsDialogClass.setTabOrder(self.trigger_del_btn, self.record_list)
        SettingsDialogClass.setTabOrder(self.record_list, self.record_add_btn)
        SettingsDialogClass.setTabOrder(self.record_add_btn, self.record_del_btn)
        SettingsDialogClass.setTabOrder(self.record_del_btn, self.ignore_list)
        SettingsDialogClass.setTabOrder(self.ignore_list, self.stop_notes_chk)
        SettingsDialogClass.setTabOrder(self.stop_notes_chk, self.stop_events_table)
        SettingsDialogClass.setTabOrder(self.stop_events_table, self.stop_events_up_btn)
        SettingsDialogClass.setTabOrder(self.stop_events_up_btn, self.stop_events_down_btn)
        SettingsDialogClass.setTabOrder(self.stop_events_down_btn, self.stop_events_add_btn)
        SettingsDialogClass.setTabOrder(self.stop_events_add_btn, self.stop_events_del_btn)
        SettingsDialogClass.setTabOrder(self.stop_events_del_btn, self.ctrl_auto_connect_chk)
        SettingsDialogClass.setTabOrder(self.ctrl_auto_connect_chk, self.ctrl_auto_connect_edit)
        SettingsDialogClass.setTabOrder(self.ctrl_auto_connect_edit, self.toggle_mode_chk)
        SettingsDialogClass.setTabOrder(self.toggle_mode_chk, self.enable_combo)
        SettingsDialogClass.setTabOrder(self.enable_combo, self.enable_param_combo)
        SettingsDialogClass.setTabOrder(self.enable_param_combo, self.enable_value_spin)
        SettingsDialogClass.setTabOrder(self.enable_value_spin, self.enable_chan_spin)
        SettingsDialogClass.setTabOrder(self.enable_chan_spin, self.disable_combo)
        SettingsDialogClass.setTabOrder(self.disable_combo, self.disable_param_combo)
        SettingsDialogClass.setTabOrder(self.disable_param_combo, self.disable_value_spin)
        SettingsDialogClass.setTabOrder(self.disable_value_spin, self.disable_chan_spin)
        SettingsDialogClass.setTabOrder(self.disable_chan_spin, self.stop_combo)
        SettingsDialogClass.setTabOrder(self.stop_combo, self.stop_param_combo)
        SettingsDialogClass.setTabOrder(self.stop_param_combo, self.stop_value_spin)
        SettingsDialogClass.setTabOrder(self.stop_value_spin, self.stop_chan_spin)
        SettingsDialogClass.setTabOrder(self.stop_chan_spin, self.fb_auto_connect_chk)
        SettingsDialogClass.setTabOrder(self.fb_auto_connect_chk, self.fb_auto_connect_edit)
        SettingsDialogClass.setTabOrder(self.fb_auto_connect_edit, self.fb_enable_table)
        SettingsDialogClass.setTabOrder(self.fb_enable_table, self.fb_enable_up_btn)
        SettingsDialogClass.setTabOrder(self.fb_enable_up_btn, self.fb_enable_down_btn)
        SettingsDialogClass.setTabOrder(self.fb_enable_down_btn, self.fb_enable_add_btn)
        SettingsDialogClass.setTabOrder(self.fb_enable_add_btn, self.fb_enable_del_btn)
        SettingsDialogClass.setTabOrder(self.fb_enable_del_btn, self.fb_disable_table)
        SettingsDialogClass.setTabOrder(self.fb_disable_table, self.fb_disable_up_btn)
        SettingsDialogClass.setTabOrder(self.fb_disable_up_btn, self.fb_disable_down_btn)
        SettingsDialogClass.setTabOrder(self.fb_disable_down_btn, self.fb_disable_add_btn)
        SettingsDialogClass.setTabOrder(self.fb_disable_add_btn, self.fb_disable_del_btn)
        SettingsDialogClass.setTabOrder(self.fb_disable_del_btn, self.fb_stop_table)
        SettingsDialogClass.setTabOrder(self.fb_stop_table, self.fb_stop_up_btn)
        SettingsDialogClass.setTabOrder(self.fb_stop_up_btn, self.fb_stop_down_btn)
        SettingsDialogClass.setTabOrder(self.fb_stop_down_btn, self.fb_stop_add_btn)
        SettingsDialogClass.setTabOrder(self.fb_stop_add_btn, self.fb_stop_del_btn)
        SettingsDialogClass.setTabOrder(self.fb_stop_del_btn, self.fb_play_table)
        SettingsDialogClass.setTabOrder(self.fb_play_table, self.fb_play_up_btn)
        SettingsDialogClass.setTabOrder(self.fb_play_up_btn, self.fb_play_down_btn)
        SettingsDialogClass.setTabOrder(self.fb_play_down_btn, self.fb_play_add_btn)
        SettingsDialogClass.setTabOrder(self.fb_play_add_btn, self.fb_play_del_btn)
        SettingsDialogClass.setTabOrder(self.fb_play_del_btn, self.buttonBox)
        SettingsDialogClass.setTabOrder(self.buttonBox, self.tabWidget)

    def retranslateUi(self, SettingsDialogClass):
        SettingsDialogClass.setWindowTitle(_translate("SettingsDialogClass", "MOL settings", None))
        self.groupBox_6.setTitle(_translate("SettingsDialogClass", "Stop events", None))
        self.stop_events_down_btn.setText(_translate("SettingsDialogClass", "▼", None))
        self.stop_events_del_btn.setText(_translate("SettingsDialogClass", "-", None))
        self.label_16.setText(_translate("SettingsDialogClass", "Events that will be sent after stopping a playing loop (e.g.: to stop all notes)", None))
        self.stop_notes_chk.setText(_translate("SettingsDialogClass", "Try to detect still playing notes and stop them", None))
        self.stop_events_up_btn.setText(_translate("SettingsDialogClass", "▲", None))
        self.stop_events_add_btn.setText(_translate("SettingsDialogClass", "+", None))
        self.groupBox_4.setTitle(_translate("SettingsDialogClass", "Input connections", None))
        self.auto_connect_hw_radio.setToolTip(_translate("SettingsDialogClass", "Automatically connect to physical devices, like hardware sound cards and USB midi devices.", None))
        self.auto_connect_hw_radio.setText(_translate("SettingsDialogClass", "Hardware ports", None))
        self.auto_connect_sw_radio.setToolTip(_translate("SettingsDialogClass", "<html><head/><body><p>Automatically connect to software devices, like sequencers or virtual keyboards.</p><p>Be aware that programs tend to send out the incoming events, this might result in repeated messages that MOL <span style=\" font-weight:600;\">cannot</span> detect and could cause unpredictable behaviour (MOL and currently active programs could even crash).<br/>You should consider using the <span style=\" font-weight:600;\">Custom ports</span> mode, and manually set to which ports MOL will try to connect to.</p></body></html>", None))
        self.auto_connect_sw_radio.setText(_translate("SettingsDialogClass", "Software ports", None))
        self.auto_connect_all_radio.setToolTip(_translate("SettingsDialogClass", "<html><head/><body><p>Automatically connect to <span style=\" font-weight:600;\">ANY</span> ALSA device, hardware and software.</p><p>Be aware that programs tend to send out the incoming events, this might result in repeated messages that MOL <span style=\" font-weight:600;\">cannot</span> detect and could cause unpredictable behaviour (MOL and currently active programs could even crash).<br/>You should consider using the <span style=\" font-weight:600;\">Custom ports</span> mode, and manually set to which ports MOL will try to connect to.</p></body></html>", None))
        self.auto_connect_all_radio.setText(_translate("SettingsDialogClass", "Any port", None))
        self.auto_connect_custom_radio.setToolTip(_translate("SettingsDialogClass", "<html><head/><body><p>Create a visible ALSA port for MOL.</p><p>If no port is selected in the alongside list, you have to manually connect MOL to the input devices you want, using a dedicated patchbay (like QJackCtl, Patchage or ALSA\'s <span style=\" font-style:italic;\">aconnect</span>).</p><p>Use the list to add devices MOL will try to automatically connect to.</p></body></html>", None))
        self.auto_connect_custom_radio.setText(_translate("SettingsDialogClass", "Custom ports", None))
        self.label_13.setText(_translate("SettingsDialogClass", "<html><head/><body><p><span style=\" font-weight:600;\">Warning</span>: to apply these settings you <span style=\" font-weight:600;\">must</span> restart MOL!</p></body></html>", None))
        self.auto_connect_list.setToolTip(_translate("SettingsDialogClass", "<html><head/><body><p>Use this list to add ports MOL will try to connect to when &quot;<span style=\" font-style:italic;\">Custom ports</span>&quot; mode is selected</p></body></html>", None))
        self.auto_connect_add_btn.setText(_translate("SettingsDialogClass", "+", None))
        self.auto_connect_del_btn.setText(_translate("SettingsDialogClass", "-", None))
        self.blacklist_del_btn.setText(_translate("SettingsDialogClass", "-", None))
        self.blacklist_add_btn.setText(_translate("SettingsDialogClass", "+", None))
        self.blacklist_list.setToolTip(_translate("SettingsDialogClass", "MOL will not try to connect to devices matching this list.", None))
        self.blacklist_lbl.setText(_translate("SettingsDialogClass", "<html><head/><body><p><span style=\" font-weight:600;\">Blacklist!</span> Devices MOL will <span style=\" font-weight:600;\">not</span> try to connect to. This list has precedence on the &quot;<span style=\" font-style:italic;\">Custom ports</span>&quot; list.</p></body></html>", None))
        self.whitelist_lbl.setText(_translate("SettingsDialogClass", "<html><head/><body><p><span style=\" font-weight:600;\">Custom whitelist!</span> Devices that MOL will try to connect to if &quot;<span style=\" font-style:italic;\">Custom ports</span>&quot; mode is selected.</p></body></html>", None))
        self.groupBox_3.setTitle(_translate("SettingsDialogClass", "Loop activation", None))
        self.trigger_list.setToolTip(_translate("SettingsDialogClass", "These events will be used to trigger a loop.\n"
"It is usually good enough to leave only Note On events, because Note Off events might occur in very different moment, and even overlap with new Note On events.", None))
        self.trigger_add_btn.setText(_translate("SettingsDialogClass", "<", None))
        self.trigger_del_btn.setText(_translate("SettingsDialogClass", ">", None))
        self.record_add_btn.setText(_translate("SettingsDialogClass", "<", None))
        self.record_del_btn.setText(_translate("SettingsDialogClass", ">", None))
        self.record_list.setToolTip(_translate("SettingsDialogClass", "Events in this list will be recorded but not used to recognize a repeated pattern.", None))
        self.label_12.setText(_translate("SettingsDialogClass", "Time tollerance threshold in milliseconds", None))
        self.label_11.setText(_translate("SettingsDialogClass", "Ignored events", None))
        self.label_9.setText(_translate("SettingsDialogClass", "Triggering events", None))
        self.label_10.setText(_translate("SettingsDialogClass", "Recorded events", None))
        self.ignore_list.setToolTip(_translate("SettingsDialogClass", "Event types in this list will always be ignored", None))
        self.groupBox.setTitle(_translate("SettingsDialogClass", "Base configuration", None))
        self.label.setText(_translate("SettingsDialogClass", "Maximum number of seconds before ignoring previous events", None))
        self.label_8.setText(_translate("SettingsDialogClass", "Maximum pattern length", None))
        self.startup_chk.setText(_translate("SettingsDialogClass", "Enable on startup", None))
        self.ignore_doublenote_chk.setText(_translate("SettingsDialogClass", "Ignore note repetition", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingsDialogClass", "General configuration", None))
        self.groupBox_2.setTitle(_translate("SettingsDialogClass", "Remote control", None))
        self.label_3.setText(_translate("SettingsDialogClass", "Disable (and stop) event:", None))
        self.label_6.setText(_translate("SettingsDialogClass", "Stop event:", None))
        self.label_2.setText(_translate("SettingsDialogClass", "Enable event:", None))
        self.toggle_mode_chk.setToolTip(_translate("SettingsDialogClass", "If enabled, uses the \"Enable\" event to toggle between enabled and disabled state. If a loop is currently playing, it will be stopped.", None))
        self.toggle_mode_chk.setText(_translate("SettingsDialogClass", "Toggle mode", None))
        self.label_7.setText(_translate("SettingsDialogClass", "Value:", None))
        self.label_5.setText(_translate("SettingsDialogClass", "Value:", None))
        self.ctrl_auto_connect_chk.setText(_translate("SettingsDialogClass", "Auto connect", None))
        self.ctrl_auto_connect_edit.setToolTip(_translate("SettingsDialogClass", "<html><head/><body><p>Type ports MOL will try to automatically connect to.<br/>The complete format is <span style=\" font-weight:600;\">client</span>:<span style=\" font-weight:600;\">port</span>, wheter as string or as numbers. For example:</p><ul><li>USB MIDI interface:USB MIDI Port 1</li><li>20:0</li></ul><p>Pattern search works using regular expressions, the string &quot;USB MIDI.*1&quot; will connect to every port with client name beginning with &quot;USB MIDI&quot; and port name ending with &quot;1&quot;.</p><p>Multiple ports can be specified, separated by a comma.</p></body></html>", None))
        self.label_4.setText(_translate("SettingsDialogClass", "Value:", None))
        self.label_20.setText(_translate("SettingsDialogClass", "Channel:", None))
        self.disable_chan_spin.setSpecialValueText(_translate("SettingsDialogClass", "Any", None))
        self.label_22.setText(_translate("SettingsDialogClass", "Channel:", None))
        self.label_21.setText(_translate("SettingsDialogClass", "Channel:", None))
        self.stop_chan_spin.setSpecialValueText(_translate("SettingsDialogClass", "Any", None))
        self.enable_chan_spin.setSpecialValueText(_translate("SettingsDialogClass", "Any", None))
        self.stop_combo.setItemText(0, _translate("SettingsDialogClass", "CTRL", None))
        self.stop_combo.setItemText(1, _translate("SettingsDialogClass", "Note ON", None))
        self.stop_combo.setItemText(2, _translate("SettingsDialogClass", "Note OFF", None))
        self.enable_combo.setItemText(0, _translate("SettingsDialogClass", "CTRL", None))
        self.enable_combo.setItemText(1, _translate("SettingsDialogClass", "Note ON", None))
        self.enable_combo.setItemText(2, _translate("SettingsDialogClass", "Note OFF", None))
        self.disable_combo.setItemText(0, _translate("SettingsDialogClass", "CTRL", None))
        self.disable_combo.setItemText(1, _translate("SettingsDialogClass", "Note ON", None))
        self.disable_combo.setItemText(2, _translate("SettingsDialogClass", "Note OFF", None))
        self.groupBox_5.setTitle(_translate("SettingsDialogClass", "Feedback", None))
        self.fb_stop_add_btn.setText(_translate("SettingsDialogClass", "+", None))
        self.fb_disable_down_btn.setText(_translate("SettingsDialogClass", "▼", None))
        self.label_15.setText(_translate("SettingsDialogClass", "Events that will be sent when enabling MOL", None))
        self.fb_auto_connect_chk.setText(_translate("SettingsDialogClass", "Auto connect", None))
        self.fb_auto_connect_edit.setToolTip(_translate("SettingsDialogClass", "<html><head/><body><p>Type ports MOL will try to automatically connect to.<br/>The complete format is <span style=\" font-weight:600;\">client</span>:<span style=\" font-weight:600;\">port</span>, wheter as string or as numbers. For example:</p><ul><li>USB MIDI interface:USB MIDI Port 1</li><li>20:0</li></ul><p>Pattern search works using regular expressions, the string &quot;USB MIDI.*1&quot; will connect to every port with client name beginning with &quot;USB MIDI&quot; and port name ending with &quot;1&quot;.</p><p>Multiple ports can be specified, separated by a comma.</p></body></html>", None))
        self.label_17.setText(_translate("SettingsDialogClass", "Events that will be sent when disabling MOL", None))
        self.label_18.setText(_translate("SettingsDialogClass", "Events that will be sent when stopping MOL", None))
        self.fb_enable_add_btn.setText(_translate("SettingsDialogClass", "+", None))
        self.fb_play_add_btn.setText(_translate("SettingsDialogClass", "+", None))
        self.fb_stop_del_btn.setText(_translate("SettingsDialogClass", "-", None))
        self.fb_play_del_btn.setText(_translate("SettingsDialogClass", "-", None))
        self.fb_enable_del_btn.setText(_translate("SettingsDialogClass", "-", None))
        self.fb_enable_up_btn.setText(_translate("SettingsDialogClass", "▲", None))
        self.fb_disable_add_btn.setText(_translate("SettingsDialogClass", "+", None))
        self.fb_disable_del_btn.setText(_translate("SettingsDialogClass", "-", None))
        self.fb_stop_up_btn.setText(_translate("SettingsDialogClass", "▲", None))
        self.fb_enable_down_btn.setText(_translate("SettingsDialogClass", "▼", None))
        self.fb_stop_down_btn.setText(_translate("SettingsDialogClass", "▼", None))
        self.label_19.setText(_translate("SettingsDialogClass", "Events that will be sent when a loop starts", None))
        self.fb_disable_up_btn.setText(_translate("SettingsDialogClass", "▲", None))
        self.fb_play_up_btn.setText(_translate("SettingsDialogClass", "▲", None))
        self.fb_play_down_btn.setText(_translate("SettingsDialogClass", "▼", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SettingsDialogClass", "MIDI interaction", None))

from mol.classes import ParamCombo
import icons_rc
